// Mock data for ORCA - Ocean Remote-sensing & Coastal Alert platform (India)

export const coastalStats = {
  networkReadiness: 92,
  sstAnomaly: "+2.1°C",
  meanWind: "18 km/h",
  lastSync: "08 MAR · 09:42 IST",
  activeAlerts: 12,
  safeFishingZones: 84,
  citizenReports: 316,
  ecosystemHealth: 72,
};

// Extensive coastal regions across India
export const regions = [
  {
    id: "gulf-of-mannar",
    name: "Gulf of Mannar",
    state: "Tamil Nadu",
    lat: 8.82,
    lng: 78.12,
    risk: "High",
    riskColor: "orange",
    ecosystemHealth: 48,
    sst: "30.4°C",
    wave: "2.4m",
    weather: "Humid / SST Anomaly",
    action: "Issue coral bleaching advisory & alert conservation squad.",
    reports: ["3 fish mortality reports", "Coral bleaching observed"],
    tag: "Coral bleaching risk · +2.1°C SST",
  },
  {
    id: "odisha-coast",
    name: "Odisha Coast",
    state: "Odisha",
    lat: 20.26,
    lng: 86.7,
    risk: "Critical",
    riskColor: "red",
    ecosystemHealth: 31,
    sst: "29.1°C",
    wave: "4.8m",
    weather: "Cyclonic depression",
    action: "Do not sail. Follow district disaster authority instructions.",
    reports: ["Cyclone alerts issued", "High wave energy reported"],
    tag: "Cyclone watch · 4.8m wave height",
  },
  {
    id: "mumbai-coast",
    name: "Mumbai Coast",
    state: "Maharashtra",
    lat: 19.07,
    lng: 72.87,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 58,
    sst: "28.2°C",
    wave: "1.6m",
    weather: "Pollution advisory",
    action: "Dispatch a verification team and contain shoreline spread.",
    reports: ["Plastic waste build-up", "Possible oil slick reported"],
    tag: "Plastic waste · possible oil slick",
  },
  {
    id: "lakshadweep",
    name: "Lakshadweep Reefs",
    state: "Lakshadweep",
    lat: 10.57,
    lng: 72.64,
    risk: "Safe",
    riskColor: "green",
    ecosystemHealth: 82,
    sst: "28.6°C",
    wave: "1.1m",
    weather: "Clear skies",
    action: "Maintain monitoring cadence & continue reef watch.",
    reports: ["Healthy reef indicators", "Turtle nesting observed"],
    tag: "Reef watch · Healthy indicators",
  },
  {
    id: "sundarbans",
    name: "Sundarbans Delta",
    state: "West Bengal",
    lat: 21.94,
    lng: 88.9,
    risk: "High",
    riskColor: "orange",
    ecosystemHealth: 51,
    sst: "29.5°C",
    wave: "2.2m",
    weather: "Storm surge risk",
    action: "Alert forest wardens; brace mangrove barriers.",
    reports: ["Mangrove die-back spotted", "Salinity rising"],
    tag: "Mangrove stress · Salinity rising",
  },
  {
    id: "kochi-coast",
    name: "Kochi Coast",
    state: "Kerala",
    lat: 9.93,
    lng: 76.26,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 63,
    sst: "29.0°C",
    wave: "2.0m",
    weather: "Monsoon advisory",
    action: "Advise coastal shipping to hold, monitor swell.",
    reports: ["Backwater flooding", "Fish landing dropped 12%"],
    tag: "Swell watch · Monsoon advisory",
  },
  {
    id: "visakhapatnam",
    name: "Visakhapatnam Coast",
    state: "Andhra Pradesh",
    lat: 17.68,
    lng: 83.21,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 66,
    sst: "28.8°C",
    wave: "1.9m",
    weather: "Port advisory",
    action: "Coordinate with port authority on outbound vessels.",
    reports: ["Turtle nesting site observed", "Beach erosion mapped"],
    tag: "Port advisory · Vessel routing",
  },
  {
    id: "goa-coast",
    name: "Goa Coastline",
    state: "Goa",
    lat: 15.29,
    lng: 73.9,
    risk: "Safe",
    riskColor: "green",
    ecosystemHealth: 78,
    sst: "28.4°C",
    wave: "1.3m",
    weather: "Fair",
    action: "Continue beach patrols & citizen outreach.",
    reports: ["Clean beach index high", "Turtle hatchling reports"],
    tag: "Reef stable · Beach index high",
  },
  {
    id: "kutch-coast",
    name: "Gulf of Kutch",
    state: "Gujarat",
    lat: 22.55,
    lng: 69.62,
    risk: "High",
    riskColor: "orange",
    ecosystemHealth: 55,
    sst: "29.2°C",
    wave: "1.7m",
    weather: "Salinity anomaly",
    action: "Deploy field survey; assess coral cover.",
    reports: ["Salinity spike", "Reef discoloration signals"],
    tag: "Coral stress · Salinity anomaly",
  },
  {
    id: "chennai-coast",
    name: "Chennai Coast",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 62,
    sst: "29.3°C",
    wave: "1.8m",
    weather: "Rip current advisory",
    action: "Deploy lifeguards; publish swim advisory.",
    reports: ["Rip current sightings", "Sea weed washout"],
    tag: "Rip current · Swim advisory",
  },
  {
    id: "puducherry-coast",
    name: "Puducherry Coast",
    state: "Puducherry",
    lat: 11.93,
    lng: 79.83,
    risk: "Safe",
    riskColor: "green",
    ecosystemHealth: 74,
    sst: "28.7°C",
    wave: "1.2m",
    weather: "Fair",
    action: "Continue eco-tourism protocols & beach cleanups.",
    reports: ["Turtle conservation active", "Community walk-through OK"],
    tag: "Eco-tourism stable",
  },
  {
    id: "mangalore-coast",
    name: "Mangalore Coast",
    state: "Karnataka",
    lat: 12.91,
    lng: 74.85,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 65,
    sst: "28.9°C",
    wave: "1.7m",
    weather: "Swell advisory",
    action: "Notify port operations & small craft.",
    reports: ["Small-craft warning", "Debris drift observed"],
    tag: "Swell watch · Debris drift",
  },
  {
    id: "andaman-islands",
    name: "Andaman Islands",
    state: "A & N Islands",
    lat: 11.74,
    lng: 92.65,
    risk: "Safe",
    riskColor: "green",
    ecosystemHealth: 86,
    sst: "28.5°C",
    wave: "1.0m",
    weather: "Clear",
    action: "Continue biosphere monitoring cadence.",
    reports: ["Reef cover stable", "Dolphin sightings up"],
    tag: "Biosphere stable",
  },
  {
    id: "paradip-coast",
    name: "Paradip Coast",
    state: "Odisha",
    lat: 20.31,
    lng: 86.61,
    risk: "High",
    riskColor: "orange",
    ecosystemHealth: 49,
    sst: "29.4°C",
    wave: "3.6m",
    weather: "Cyclone watch",
    action: "Secure port operations; suspend outbound sailing.",
    reports: ["Storm surge alerts", "High wave energy"],
    tag: "Cyclone watch · Port hold",
  },
  {
    id: "diu-coast",
    name: "Diu Coast",
    state: "Daman & Diu",
    lat: 20.71,
    lng: 70.99,
    risk: "Safe",
    riskColor: "green",
    ecosystemHealth: 77,
    sst: "28.6°C",
    wave: "1.2m",
    weather: "Fair",
    action: "Continue routine coastal patrols.",
    reports: ["Beach index stable"],
    tag: "Beach index stable",
  },
  {
    id: "kanyakumari",
    name: "Kanyakumari Cape",
    state: "Tamil Nadu",
    lat: 8.08,
    lng: 77.54,
    risk: "Moderate",
    riskColor: "yellow",
    ecosystemHealth: 60,
    sst: "29.1°C",
    wave: "2.0m",
    weather: "Wind advisory",
    action: "Advise catamarans to delay departure.",
    reports: ["Wind gusts logged", "Fishery landings mixed"],
    tag: "Wind advisory · Delayed sailing",
  },
];

export const alerts = [
  {
    id: "a1",
    level: "Critical",
    status: "Active",
    title: "Cyclone & high-wave warning",
    location: "Odisha Coast · Kendrapara",
    cause: "Cyclonic depression moving north-west",
    response: "Do not sail. Follow district disaster authority instructions.",
    time: "09:14 IST",
  },
  {
    id: "a2",
    level: "High",
    status: "Monitoring",
    title: "Coral bleaching risk",
    location: "Gulf of Mannar · Tuticorin",
    cause: "Sea surface temperature +2.1°C above normal",
    response: "Inspect local water quality and pause reef-adjacent activity.",
    time: "08:58 IST",
  },
  {
    id: "a3",
    level: "Moderate",
    status: "Monitoring",
    title: "Possible oil pollution",
    location: "Mumbai Coast · Sewri",
    cause: "Citizen report matched to a dark surface slick",
    response: "Dispatch a verification team and contain shoreline spread.",
    time: "07:42 IST",
  },
  {
    id: "a4",
    level: "High",
    status: "Monitoring",
    title: "Mangrove stress signal",
    location: "Sundarbans · South 24 Parganas",
    cause: "Salinity rising, satellite NDVI drop observed",
    response: "Alert forest wardens and reinforce protective barriers.",
    time: "06:31 IST",
  },
  {
    id: "a5",
    level: "Moderate",
    status: "Monitoring",
    title: "Rip current advisory",
    location: "Chennai Coast · Marina",
    cause: "Wave interaction with tidal drift",
    response: "Deploy lifeguards & publish public swim advisory.",
    time: "05:22 IST",
  },
  {
    id: "a6",
    level: "High",
    status: "Active",
    title: "Storm surge watch",
    location: "Paradip · Jagatsinghpur",
    cause: "Deep depression track, surge model at 2.4m",
    response: "Evacuate low-lying pockets, secure fishing craft.",
    time: "04:10 IST",
  },
];

export const modules = [
  { idx: "01", tag: "Observation layers", title: "Satellite Ocean View", desc: "Read the sea through temperature, colour, chlorophyll, rain and wave signals.", icon: "Satellite" },
  { idx: "02", tag: "Living systems", title: "Ecosystem Health", desc: "See how reefs, mangroves, fish habitats and beaches are holding up.", icon: "Fish" },
  { idx: "03", tag: "Risk operations", title: "Coastal Alert Centre", desc: "Move from early warning to a clear, human response plan.", icon: "AlertTriangle" },
  { idx: "04", tag: "Sea-ready guidance", title: "Fisherman Support", desc: "Find safer routes, fishing windows and a clear no-sail signal.", icon: "Anchor" },
  { idx: "05", tag: "Community signal", title: "Citizen Reports", desc: "Turn a shoreline observation into a traceable response workflow.", icon: "Camera" },
  { idx: "06", tag: "Explainable intelligence", title: "ORCA AI Reasoning Engine", desc: "Understand why a risk is rising and what teams should do next.", icon: "BrainCircuit" },
];

export const districts = [
  { id: "tuticorin", name: "Tuticorin, Tamil Nadu", wave: "2.4m", wind: "28 km/h", window: "06:00–09:30", pfz: "Confirmed", advisory: "Do Not Sail", advisoryLevel: "danger", note: "High wave energy and wind create unsafe conditions for small craft.", lat: 8.76, lng: 78.13 },
  { id: "chennai", name: "Chennai, Tamil Nadu", wave: "1.8m", wind: "19 km/h", window: "05:30–10:00", pfz: "Confirmed", advisory: "Sail with caution", advisoryLevel: "warning", note: "Rip current advisory active near Marina beach.", lat: 13.08, lng: 80.27 },
  { id: "kochi", name: "Kochi, Kerala", wave: "2.0m", wind: "22 km/h", window: "05:45–09:45", pfz: "Confirmed", advisory: "Sail with caution", advisoryLevel: "warning", note: "Monsoon swell active, keep close to shore.", lat: 9.93, lng: 76.26 },
  { id: "visakhapatnam", name: "Visakhapatnam, Andhra Pradesh", wave: "1.9m", wind: "20 km/h", window: "05:30–10:15", pfz: "Confirmed", advisory: "Safe window", advisoryLevel: "safe", note: "Small vessels can operate within the recommended window.", lat: 17.68, lng: 83.21 },
  { id: "paradip", name: "Paradip, Odisha", wave: "3.6m", wind: "38 km/h", window: "—", pfz: "Suspended", advisory: "Do Not Sail", advisoryLevel: "danger", note: "Cyclonic depression, all outbound sailing suspended.", lat: 20.31, lng: 86.61 },
  { id: "mumbai", name: "Mumbai, Maharashtra", wave: "1.6m", wind: "18 km/h", window: "06:15–10:00", pfz: "Confirmed", advisory: "Safe window", advisoryLevel: "safe", note: "Suitable window; watch for pollution flags near Sewri.", lat: 19.07, lng: 72.87 },
  { id: "panaji", name: "Panaji, Goa", wave: "1.3m", wind: "14 km/h", window: "05:30–10:30", pfz: "Confirmed", advisory: "Safe window", advisoryLevel: "safe", note: "Clear conditions, extended fishing window.", lat: 15.5, lng: 73.83 },
  { id: "mangalore", name: "Mangalore, Karnataka", wave: "1.7m", wind: "20 km/h", window: "05:45–09:45", pfz: "Confirmed", advisory: "Sail with caution", advisoryLevel: "warning", note: "Debris drift observed near shipping lane.", lat: 12.91, lng: 74.85 },
  { id: "port-blair", name: "Port Blair, A & N", wave: "1.0m", wind: "12 km/h", window: "05:15–11:00", pfz: "Confirmed", advisory: "Safe window", advisoryLevel: "safe", note: "Clear tropical conditions, calm seas.", lat: 11.62, lng: 92.72 },
  { id: "kavaratti", name: "Kavaratti, Lakshadweep", wave: "1.1m", wind: "13 km/h", window: "05:30–10:30", pfz: "Confirmed", advisory: "Safe window", advisoryLevel: "safe", note: "Reef-safe travel corridor active.", lat: 10.57, lng: 72.64 },
];

export const reasoningSteps = [
  { n: "01", title: "Observation", desc: "Sea surface temperature is 2.1°C above the seasonal baseline." },
  { n: "02", title: "Ecosystem signal", desc: "Coral health is declining, increasing local bleaching probability." },
  { n: "03", title: "Community evidence", desc: "Three citizen reports indicate fish deaths near the coast." },
];

export const roles = [
  { title: "Fishermen", desc: "Receive safety and fishing-zone guidance.", icon: "Anchor" },
  { title: "Citizens", desc: "Report pollution or injured animals.", icon: "Users" },
  { title: "Researchers", desc: "Validate ecosystem observations.", icon: "Microscope" },
  { title: "NGOs", desc: "Organize cleanup actions.", icon: "Handshake" },
  { title: "Authorities", desc: "Monitor high-risk zones.", icon: "ShieldCheck" },
];

export const workflow = ["Reported", "AI Analyzed", "Verified", "Action Started", "Resolved"];

export const issueTypes = ["Plastic Waste", "Oil Spill", "Coral Bleaching", "Fish Mortality", "Injured Marine Animal", "Illegal Fishing", "Beach Erosion", "Algal Bloom"];
